//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Account.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Account
    {

        [Key]
        [Required]
        public int RefNo { get; set; }
        [Required (ErrorMessage ="*")]
        [MaxLength(8, ErrorMessage = "Account Number cannot be longer than 8 digits")]
        public string AccountNumber { get; set; }
        [Required(ErrorMessage = "*")]

        public string AccountHolder { get; set; }
        [Required(ErrorMessage = "*")]
        public Nullable<decimal> CurrentBalace { get; set; }
        [Required(ErrorMessage = "*")]
        public string BankName { get; set; }
        [Required(ErrorMessage = "*")]
        public Nullable<System.DateTime> OpeningDate { get; set; }
        [Required(ErrorMessage = "*")]
        public Nullable<bool> IsActive { get; set; }
    }
}
